version: 3.0.{build}-pre
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.AspNetCore.Serilog\Elmah.Io.AspNetCore.Serilog.csproj --output artifacts
test:
  assemblies:
    only:
    - test\Elmah.Io.AspNetCore.Serilog.Tests\bin\**\Elmah.Io.AspNetCore.Serilog.Tests.dll
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 9XpSybqiIbTFiTdfkpUaBSMdLFCm4yx/MYR7KtYbV18g5gP5L6U8bhhOPfi/56o+